config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  patch 'products/:id/inline_update', to: 'products#inline_update', as: 'inline_update_product'
  resources :products
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  scope :purchased, -> { where(purchased: true) }
  scope :remaining, -> { where(purchased: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.includes(:products)
    @total_price = Product.sum(:price)
    @total_purchased = Product.purchased.sum(:price)
    @total_remaining = Product.remaining.sum(:price)
  end

  def show; end
  def edit; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show; end
  def edit; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
    end
  end

  def inline_update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      render json: { status: 'success', message: 'Product updated' }
    else
      render json: { status: 'error', message: 'Product update failed' }
    end
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :url, :purchased, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="card col-6 p-5 shadow">
  <h6 class="text-success text-center">
    <%= category.name %>
  </h6>
</div>

app/views/categories/_form.html.erb
<div class="card p-5 shadow col-6">
  <%= form_with(model: category) do |form| %>

    <% if category.errors.any? %>
      <p><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved</p>
      <% category.errors.each do |error| %>
        <p><%= error.full_message %></p>
      <% end %>
    <% end %>

    <div>
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name %>
    </div>

    <div class="mt-5">
      <%= form.submit class: "btn btn-sm btn-success" %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mb-5">
  Editing category
</h1>

<%= render "form", category: @category %>
<br>
<div class="float-end">
  <%= link_to "Show category", @category %><br>
  <%= link_to "Back to categories", categories_path, class: "text-secondary" %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="border p-3 text-center bg-light">
  Total Price:     <%= number_to_currency(@total_price) %>
</h1>
<h4 class="border p-3 text-center bg-light">
  Total Purchased: <%= number_to_currency(@total_purchased) %>
</h4>
<h4 class="border p-3 text-center bg-light">
  Total Remaining: <%= number_to_currency(@total_remaining) %>
</h4>
<br>

<% @categories.each do |category| %>
  <h3 class="text-center my-2">
    <span class="text-muted"><%= category.name %></span> - <%= number_to_currency(category.products.sum(:price)) %>
  </h3>

  <table class="table table-bordered table-primary mb-5">
    <thead>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Purchased</th>
        <th>URL</th>
        <th>Product Page</th>
      </tr>
    </thead>

    <tbody data-controller="products">
      <% category.products.each do |product| %>
        <tr>
          <td
            class="editable"
            contenteditable="true"
            data-model="product"
            data-attribute="name"
            data-url="<%= inline_update_product_path(product) %>">
            <%= product.name %>
          </td>
          <td
            class="editable"
            contenteditable="true"
            data-model="product"
            data-attribute="price"
            data-url="<%= inline_update_product_path(product) %>">
            <%= number_to_currency(product.price) %>
          </td>
          <td>
            <%= check_box_tag "product_#{product.id}", true, product.purchased, class: "purchased_chackbox", data: { url: inline_update_product_path(product) } %>
          </td>
          <td
            class="editable"
            contenteditable="true"
            data-model="product"
            data-attribute="url"
            data-url="<%= inline_update_product_path(product) %>">
            <%= product.url %>
          </td>
          <td>
            <%= link_to "Show Product", product, class: "text-success" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<h6 class="p-3 shadow bg-light my-5 text-center">
  <%= link_to "Create Category", new_category_path, class: "text-success" %>
</h6>

app/views/categories/new.html.erb
<h1 class="text-center mb-5">
  New category
</h1>

<%= render "form", category: @category %>
<br>
<div class="float-end">
  <%= link_to "Back to categories", categories_path, class: "text-secondary" %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>
<div class="float-end">
  <%= link_to "Edit category", edit_category_path(@category) %><br>
  <%= link_to "Back to categories", categories_path, class: "text-secondary" %>
  <%= button_to "Destroy this category", @category, method: :delete, class: "m-0 p-0 btn btn-link text-decoration-none text-danger" %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand me-5" href="/">Shopping</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse ms-5" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= new_category_path %>">Create category</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= new_product_path %>">Create product</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= categories_path %>">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= products_path %>">Products</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
      <%= render "layouts/nav" %>
    </header>

    <main class="container p-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<div class="card p-5 shadow col-6">
  <%= form_with(model: product) do |form| %>

    <% if product.errors.any? %>
      <p><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved</p>
      <% product.errors.each do |error| %>
        <p><%= error.full_message %></p>
      <% end %>
    <% end %>

    <div>
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div>
      <%= form.label :price, class: "form-label" %>
      <%= form.text_field :price, class: "form-control" %>
    </div>

    <div>
      <%= form.label :url, class: "form-label" %>
      <%= form.text_field :url, class: "form-control" %>
    </div>

    <div>
      <%= form.label :purchased, class: "form-label" %>
      <%= form.check_box :purchased, class: "form-control" %>
    </div>

    <div>
      <%= form.label :category_id, class: "form-label" %>
      <%= form.text_field :category_id, class: "form-control" %>
    </div>

    <div class="mt-3">
      <%= form.submit class: "btn btn-sm btn-success" %>
    </div>
  <% end %>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class="card col-6 p-5 shadow">
  <h5 class="text-muted text-center mb-3">
    <%= product.name %>
  </h5>

  <strong class="text-muted">
    Price:
  </strong><br>
  <small>
    $ <%= product.price %>
  </small><hr>

  <strong class="text-muted">
    Url:
  </strong><br>
  <small>
    <%= product.url %>
  </small><hr>

  <strong class="text-muted">
    Purchased:
  </strong><br>
  <small>
    <%= product.purchased %>
  </small><hr>

  <strong class="text-muted">
    Category:
  </strong><br>
  <small>
    <%= product.category.name %>
  </small>
</div>

app/views/products/edit.html.erb
<h1 class="text-center mb-5">
  Editing product
</h1>

<%= render "form", product: @product %>
<br>
<div class="float-end">
  <%= link_to "Show product", @product, class: "text-success" %>
  <%= link_to "Back to products", products_path, class: "text-secondary" %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center mb-5">
  Products
</h1>

<% @products.each do |product| %>
  <%= render product %>
  <p><%= link_to "Show product", product %></p>
<% end %>

<div class="p-3 shadow bg-light my-5 text-center">
  <%= link_to "Create Product", new_product_path, class: "text-success" %>
</div>

app/views/products/new.html.erb
<h1 class="text-center mb-5">
  New product
</h1>

<%= render "form", product: @product %>
<br>
<div class="float-end">
  <%= link_to "Back to products", products_path, class: "text-secondary" %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>
<div class="float-end">
  <%= link_to "Edit product", edit_product_path(@product) %><br>
  <%= link_to "Back to products", products_path, class: "text-secondary" %>
  <%= button_to "Destroy this product", @product, method: :delete, class: "m-0 p-0 btn btn-link text-decoration-none text-danger" %>
</div>